services:
  - type: web
    name: klekovina
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 3000
